[project]
name = "migration"
version = "0.1.0"
description = "Add a short description here"
authors = [{ name = "Ian Zhang", email = "yianzhang14@gmail.com" }]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.12.*"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.2,<3"
tqdm = ">=4.66.5,<5"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.9.2,<4"
pyarrow = ">=17.0.0,<18"
openpyxl = ">=3.1.5,<4"
bs4 = ">=4.12.3,<5"
requests = ">=2.32.3,<3"
geopandas = ">=1.0.1,<2"
proj = ">=9.5.1,<10"
pandas-stubs = ">=2.2.3.241126,<3"
haversine = ">=2.9.0,<3"
arviz = ">=0.13.0,<1"
ipywidgets = ">=8.1.8,<9"
jupyter = ">=1.1.1,<2"
tomlkit = "<0.15.1"

[tool.pixi.target.linux-64.pypi-dependencies]
jax = { version = ">=0.11.0", extras = ["cuda12"] }

[tool.pixi.pypi-dependencies]
xlogit = ">=0.2.7, <0.3"
# cupy-cuda12x = ">=13.3.0, <14"
biogeme = ">=3.3.2, <4"
openrouteservice = ">=2.3.3,<3"

[tool.ruff]
target-version = "py312"
