# columns each alternative has a measure of for each person
# this is specifically the list of columns used in the modeling notebooks
ALT_VARYING_SUFFIXES = [
    "CBSA",
    "COLLEGE_PROP",
    "DIST",
    "ENT_JOBS_PROP",
    "FOREIGN_BORN_PROP",
    "HH_MED_INC",
    "HH_WITH_CHILD_PROP",
    "HOUSE_VACANCY_PROP",
    "MED_HOUSE_VALUE_OVER_MED_HH_INC",
    "MED_RENT_PROP_HH_INC",
    "MED_TRAVEL_TIME",
    "MIL_PROP",
    "OWN_AGE_PROP",
    "OWN_NAICS_GROUP_PROP",
    "OWN_RACE_ETH_PROP",
    "STATE",
    "TOT_POP",
    "TYPE",
]

# columns that each person has a single value of, constant across alternatives
# this is specifically the list of columns used in the modeling notebooks
INDIV_COLS = [
    "CHOSEN",
    "STAY",
    "AAPI",
    "AGE_18_22",
    "AGE_18_34",
    "AGE_23_29",
    "AGE_30_39",
    "AGE_35_64",
    "AGE_40_49",
    "AGE_50_64",
    "AGE_OVER_65",
    "BLACK",
    "CHILD",
    "CHILD_6_TO_17",
    "CHILD_UNDER_6",
    "EDU_BACHELORS",
    "EDU_HIGH",
    "EDU_NOHIGH",
    "FOREIGN",
    "House vacancy proportion.ORIG",
    "INDIAN",
    "IN_COLLEGE",
    "IN_MILITARY",
    "LATINO",
    "MARRIED_MORE_THAN_YEAR",
    "Median Household Income (In 2018 Inflation Adjusted Dollars).Median Household Income (In 2018 Inflation Adjusted Dollars).SE_A14006_001.ORIG",
    "Median gross rent as a percentage of household income.ORIG",
    "Median house value over median household income.ORIG",
    "Median travel time.ORIG",
    "NAICS_AGR_EXT",
    "NAICS_GOODS_TRADE",
    "NAICS_GOVT",
    "NAICS_GROUP_PROP_AGR_EXT.ORIG",
    "NAICS_GROUP_PROP_GOODS_TRADE.ORIG",
    "NAICS_GROUP_PROP_GOVT.ORIG",
    "NAICS_GROUP_PROP_HIGH_ED.ORIG",
    "NAICS_GROUP_PROP_LICENSE.ORIG",
    "NAICS_HIGH_ED",
    "NAICS_LICENSE",
    "NAME_NUM.ORIG",
    "OTHER_RACE",
    "POBP",
    "Proportion alternative commute.ORIG",
    "Proportion foreign born.ORIG",
    "Proportion of households with children.ORIG",
    "Proportion of people 18-34.ORIG",
    "Proportion of people 35-64.ORIG",
    "Proportion of people 65+.ORIG",
    "Proportion of people AAPI.ORIG",
    "Proportion of people Black.ORIG",
    "Proportion of people Indian.ORIG",
    "Proportion of people Latino.ORIG",
    "Proportion of people White.ORIG",
    "Proportion of people other race.ORIG",
    "Proportion of people in college.ORIG",
    "Proportion of people in military.ORIG",
    "RECENTLY_MARRIED",
    "RECENTLY_WIDOWED_OR_DIVORCED",
    "SINGLE_PARENT",
    "ORIGIN_STATE",
    "TYPE_NUM.ORIG",
    "Unemployment rate.ORIG",
    "WHITE",
    "WORK1_MAR",
    "WORK2_MAR",
    "Total Population.Total Population.SE_A00001_001.ORIG",
    "Proportion of entertainment jobs.ORIG",
]
